### ISSUE TITLE
Bugs: documentSymbol items via expandItem does not work

### ISSUE THREAD

**Issue by kamecha** [uga-rosa/ddu-source-lsp#34]
`lsp_callHierachy` item support ddu's tree item and `expandItem` action.

However `lsp_documnetSymbol` item support only ddu's tree item. it seems not support `expandItem`.

when I fire `expandItem` action on `lsp_documnetSymbol`, all item is expanded regardless of it's parent item.

So `lsp_documnetSymbol` should consider `args.parent` like `lsp_callHierachy` bellow. I think.
https://github.com/uga-rosa/ddu-source-lsp/blob/fa5bc28d774e8356ef49013250df14ae65893d33/denops/%40ddu-sources/lsp_callHierarchy.ts#L81-L92

**Comment by uga-rosa** [comment]
I updated. Can you try it?

**Comment by kamecha** [comment]
Thank you for the correction
It now works as intended 👍
